### ISSUE TITLE
Pick-and-place move failures

### ISSUE THREAD

**Issue by rimvydasrub** [peterdavidfagan/mujoco_robot_environments#5]
The following script

```python
import random, time
from mujoco_robot_environments.tasks.rearrangement import RearrangementEnv

env = RearrangementEnv(viewer=True)
env.reset()
# choose a random prop to pick and place
pick_prop = random.choice(env.props)
pick_id = pick_prop.name.split('_')[-1]
place_id = pick_prop.name
# pick the prop using pick id (indexing env.props_info)
pick_pose = env.prop_pick(pick_id)
env.pick(pick_pose)
# place the prop using place id (indexing env.props)
place_pose = env.prop_place(place_id)
env.place(place_pose)

time.sleep(10)


```

leads to following error

```bash
zero-size array to reduction operation minimum which has no identity
prop_id:  95
local variable 'bbox_corners' referenced before assignment
```

there are actually two issues:
- prop_place and prop_pick requires two differenty ids (commig from either self.prop or self.props_info) Prefered options would be to use props_info ids.
- resolve the error due to rendering

**Comment by peterdavidfagan** [comment]
> prop_place and prop_pick requires two differenty ids (commig from either self.prop or self.props_info) Prefered options would be to use props_info ids.

Agree on this point, I will push a change to address this. 

> resolve the error due to rendering

The error message seems unusual, have you tried providing suitable min/max poses. I think the default behaviour of when none is provided is not correct. In general I haven't used this method without these parameters. 

Will take a look tomorrow morning.

**Comment by peterdavidfagan** [comment]
https://github.com/peterdavidfagan/mujoco_robot_environments/blob/1a72c9bb1d509c73ef4ee71effc3960d9b2f6419/mujoco_robot_environments/tasks/rearrangement.py#L617

This line is the culprit. When the object is out of view of the camera you will get the above error. You want to generate both the pick/place pose first and then execute. This isn't well documented, I'll look to add documentation and/or a fix so the collision checking doesn't call props_info which will look to render.

**Comment by peterdavidfagan** [comment]
```python
import random, time
from mujoco_robot_environments.tasks.rearrangement import RearrangementEnv

env = RearrangementEnv(viewer=True)
env.reset()

pick_prop = random.choice(env.props)

pick_id = pick_prop.name.split('_')[-1]
place_id = pick_prop.name

pick_pose = env.prop_pick(pick_id)
place_pose = env.prop_place(place_id)

env.pick(pick_pose)
env.place(place_pose)

time.sleep(10)
```

**Comment by rimvydasrub** [comment]
I confirm that executing in such manner (first estimate both poses and then do pick and place) works
